service: logconsulting
configValidationMode: off

provider:
  name: scaleway
  scwToken: ${env:SCW_SECRET_KEY}
  scwProject: ${env:SCW_PROJECT_ID}
  scwRegion: ${env:SCW_REGION}

plugins:
  - serverless-scaleway-functions

custom:
  containers:
    logconsulting:
      description: Site internet de LOG
      directory: .
      maxScale: 1
      memoryLimit: 128
      minScale: 1
      port: 80
      custom_domains:
        - log.consulting
