name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn 

      - name: Build project
        run: yarn astro build --experimental-integrations 

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build 
          path: dist 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install -g serverless serverless-scaleway-functions  

      - name: Deploy project
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
        run: |
          docker run --rm -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock -e SCW_SECRET_KEY -e SCW_PROJECT_ID docker:latest sh -c 'cd /app && serverless deploy'
