name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: node:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: yarn 

      - name: Build project
        run: yarn astro build --experimental-integrations 

      - name: Serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-scaleway-functions && serverless deploy"
          entrypoint: /bin/sh
        env:
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
          SCW_REGION: ${{ secrets.SCW_REGION }}